[package]
name = "damus"
version = "0.1.0"
authors = ["William Casarin <jb55@jb55.com>"]
edition = "2021"
#rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
#egui-android = { git = "https://github.com/jb55/egui-android.git" }  
egui = "0.22.0"
eframe = { version = "0.22.0", default-features = false, features = [ "glow", "wgpu", "android-native-activity" ] }
#eframe = "0.22.0"
egui_extras = { version = "0.22.0", features = ["image", "svg"] }
ehttp = "0.2.0"
image = { version = "0.24", features = ["jpeg", "png", "webp"] }
log = "0.4.17"
poll-promise = { git = "https://github.com/EmbarkStudios/poll-promise", rev = "b493586107b0e508860aa2e9d18049fd8cd9d13f" } # todo: update to 0.2.1 when it's released. 0.2.0 was crashing on m1
serde_derive = "1"
serde = { version = "1", features = ["derive"] } # You only need this if you want app persistence
tracing = "0.1.37"
#wasm-bindgen = "0.2.83"
nostrdb = { git = "https://github.com/damus-io/nostrdb-rs.git", rev = "2c0d43497d626e61a8de7a1efaff13d44e30d556" }
enostr = { path = "enostr" } 
serde_json = "1.0.89"
env_logger = "0.10.0"
shatter = "0.1.1"
puffin_egui = { version = "0.22.0", optional = true }
puffin = { version = "0.16.0", optional = true }

[features]
default = []
profiling = ["puffin", "puffin_egui", "eframe/puffin"]

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.16", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3"


[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.1"
android-activity = { version = "0.4", features = [ "native-activity" ] }
#winit = "0.28.6"
winit = { version = "0.28", features = [ "android-native-activity" ] }
#winit = { git="https://github.com/rust-windowing/winit.git", rev = "2a58b785fed2a3746f7c7eebce95bce67ddfd27c", features = ["android-native-activity"] }

[package.metadata.android]
package = "com.damus.app"
apk_name = "damus"
#build_targets = ["armv7-linux-androideabi", "aarch64-linux-android" ]

[package.metadata.android.sdk]
min_sdk_version = 22
target_sdk_version = 30
#max_sdk_version = 29
#assets = "assets"

[[package.metadata.android.uses_feature]]
name = "android.hardware.vulkan.level"
required = true
version = 1

[[package.metadata.android.uses_permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"
max_sdk_version = 30

[package.metadata.android.signing.release]
path = "damus.keystore"
keystore_password = "damuskeystore"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.application]
label = "Damus"
